[package]
name = "bindgen-integration"
description = "A package to test various bindgen features"
version = "0.1.0"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>"]
publish = false
build = "build.rs"

[build-dependencies]
bindgen = { path = ".." }
gcc = "0.3"

[features]
llvm_stable = ["bindgen/llvm_stable"]
