language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

os:
  - linux

rust:
  - stable
  - nightly

env:
  - LLVM_VERSION=3.8 BINDGEN_FEATURES=llvm_stable
  - LLVM_VERSION=3.9 BINDGEN_FEATURES=

cache:
  directories:
    - $HOME/.cargo

before_install: . ./ci/before_install.sh

script:
  - cargo build --verbose --features "$BINDGEN_FEATURES"
  - cargo test --features "$BINDGEN_FEATURES"
  - cargo build --release --verbose --features "$BINDGEN_FEATURES"
  - cargo test --release --features "$BINDGEN_FEATURES"
  - git add -A
  - git diff @
  - git diff-index --quiet HEAD
  - cargo test -p tests_expectations
  - cargo build --features "$BINDGEN_FEATURES _docs"

notifications:
  webhooks: http://build.servo.org:54856/travis
