language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

os:
  - linux

rust:
  - stable

env:
  global:
    - CARGO_TARGET_DIR=/tmp/bindgen
  matrix:
    - LLVM_VERSION=3.8.1
    - LLVM_VERSION=3.9.0
    - LLVM_VERSION=4.0.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.llvm-builds

before_install: . ./ci/before_install.sh

script:
  # - ./ci/assert-rustfmt.sh
  - BINDGEN_FEATURES="$BINDGEN_FEATURES" ./ci/assert-docs.sh
  - BINDGEN_FEATURES="$BINDGEN_FEATURES" ./ci/test.sh
  - ./ci/test-book.sh

after_success:
  - test "$TRAVIS_PULL_REQUEST" == "false" &&
    test "$TRAVIS_BRANCH" == "master" &&
    ./ci/deploy-book.sh

notifications:
  webhooks: http://build.servo.org:54856/travis
